/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountUp: typeof import('./src/components/Dashboard/CountUp.vue')['default']
    ECharts: typeof import('./src/components/Dashboard/ECharts.vue')['default']
    ExportButton: typeof import('./src/components/Export/ExportButton.vue')['default']
    FileUpload: typeof import('./src/components/Upload/FileUpload.vue')['default']
    FunnelChart: typeof import('./src/components/Charts/FunnelChart.vue')['default']
    GraphChart: typeof import('./src/components/Charts/GraphChart.vue')['default']
    ImageUpload: typeof import('./src/components/Upload/ImageUpload.vue')['default']
    KPIGauge: typeof import('./src/components/Dashboard/KPIGauge.vue')['default']
    RadarChart: typeof import('./src/components/Charts/RadarChart.vue')['default']
    ReportList: typeof import('./src/components/Report/ReportList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SankeyChart: typeof import('./src/components/Charts/SankeyChart.vue')['default']
    StatCard: typeof import('./src/components/Dashboard/StatCard.vue')['default']
    TimeSlider: typeof import('./src/components/Dashboard/TimeSlider.vue')['default']
    WordCloud: typeof import('./src/components/Charts/WordCloud.vue')['default']
  }
}
